#ifndef COSTANTS_H
#define COSTANTS_H

#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1


#define ERROR_FROM_WORKER 666
#define ASKING_BLOCK_TO_MASTER 10
#define SENDING_THREE_BLOCKS_TO_MASTER 11
#define SENDING_IMAGE_TO_MASTER 12
#define SENDING_BLOCK_TO_WORKER 13
#define STOPPING_PROCESS 14
#define SENDING_STATS 15
#define WAITING_PROCESS 16

#endif