#include "../include/io.h"
#include <stdio.h>


int write_ppm_image( const void * restrict image,
			    const int             xsize,
			    const int             ysize,
			    const char * restrict image_name)
{
  FILE* image_file; 
  image_file = fopen(image_name, "w"); 

  if ( image_file == NULL )
    return 1;
  

  fprintf(image_file, "P6\n# generated by\n# put here your name\n%d %d\n%d\n", xsize, ysize, 255);
  

  fwrite( image, 3, (size_t)xsize*(size_t)ysize, image_file);  

  fclose(image_file); 
  return 0;
}
